### ISSUE TITLE
[Question] AccessToken을 DB에 저장하는 이유 

### ISSUE THREAD

**Issue by wjdrbs96** [mash-up-kr/Kkyuni_Spring#45]
## `질문`

현재 `Google Login` 응답으로 `AccessToken`, `RefreshToken`을 응답으로 주고 있습니다! 저는 지금까지 프로젝트 할 때 주로 `RefreshToken`만 DB에 저장해서 사용했는데요!  

그런데 지금 현재 구현된 걸로 보면 `AccessToken`, `RefreshToken` 둘 다  Member Entity에 같이 저장을 하고 있습니다!

이렇게 구현하신 이유가 무엇인지 궁금합니다 🤔

지금까지 제가 JWT를 사용할 때는 `AccessToken`의 의도는 해당 API의 `권한`이 있는지? 체크를 하는 용도고, `RefreshToken`은 `AccessToken`이 만료되었을 때 재발급 하기 위함으로 사용해왔는데요! 😀

이런 의도라면 `AccessToken`은 Member Entity에 저장하지 않아도 될 거 같은데, `시영이형님`은 혹시 어떻게 생각하시는지~? 또한 의견은 어떠신지 여쭈어 보고 싶습니다! 🤔

<br>

![스크린샷 2021-10-28 오전 12 23 55](https://user-images.githubusercontent.com/45676906/139096633-300e8813-a466-4ab1-a5a1-ef3e7644db21.png)

그리고 만약 AccessToken이 변조 되었거나, 만료되었거나 같은 상황은 위의 코드로 검증이 가능하다고 생각해서 따로 DB에 저장하지 않아도 된다고 생각하였습니다~!

**Comment by Yangsiyoung** [comment]
아 맞아요 AccessToken 저장안해도 괜찮은데, 개발하다가 엑세스토큰 까먹었을때, 디비에서 꺼내서 쓸려고 편의상 넣어두었어요~!!
제거하는게 맞아보여요!! 제거합시다리~~~
